user:
    resource: "@userBundle/Resources/config/routing.yml"
    prefix:   /

bdls_projet:
    resource: "@BdlsProjetBundle/Resources/config/routing.yml"
    prefix:   /


#Route pour fos 
#secure_area en plus
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


#Configuration de hwi
#hwi_github_login was also added which is same as the callback url given during creation of Github application. 
#This is the url which will be intercepted by the firewall to check authentication.
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

#is same as the callback url given during creation of Github application. 
#This is the url which will be intercepted by the firewall to check authentication.
hwi_github_login:
    pattern: /login/check-github
hwi_google_login:
    pattern: /login/check-google
hwi_facebook_login:
    pattern: /login/check-facebook
    pattern: /login/check-facebook