user:
    resource: "@userBundle/Resources/config/routing.yml"
    prefix:   /

bdls_projet:
    resource: "@BdlsProjetBundle/Resources/config/routing.yml"
    prefix:   /

bdls_projet:
    resource: "@BdlsProjetBundle/Resources/config/routing.yml"
    prefix:   /
