<?php

namespace PollBundle\Repository;

/**
 * DatePollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatePollRepository extends \Doctrine\ORM\EntityRepository
{
}
