<?php

namespace PollBundle\Repository;

/**
 * DateChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
