<?php

namespace PollBundle\Repository;

/**
 * DateVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
