<?php

namespace PollBundle\Repository;

/**
 * PlaceChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
