<?php

namespace PollBundle\Repository;

/**
 * PlacePollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacePollRepository extends \Doctrine\ORM\EntityRepository
{
}
