<?php

namespace PollBundle\Repository;

/**
 * PlaceVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
