<?php

namespace PollBundle\Repository;

/**
 * TextChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
