<?php

namespace PollBundle\Repository;

/**
 * TextVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
