<?php

namespace PollBundle\Repository;

/**
 * TextPollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextPollRepository extends \Doctrine\ORM\EntityRepository
{
}
