parameters:
#    bdls_projet.example.class: Bdls\ProjetBundle\Example

services:
#    bdls_projet.example:
#        class: %bdls_projet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
